from __future__ import annotations

import io
import json
import zipfile
from typing import Iterable

from .session import Session


def build_env(session: Session) -> str:
    camera_url = session.get_camera_url() or ""
    bev = session.get_bev()
    src_points_json = (
        json.dumps(bev["src_points"], separators=(",", ":")) if bev else ""
    )
    bev_w = bev["width"] if bev else 1200
    bev_h = bev["height"] if bev else 800
    return (
        "# Generated by parking-configurator\n"
        "\n"
        "# Camera RTSP stream\n"
        f"CAMERA_URL={camera_url}\n"
        "\n"
        "# BEV calibration: 4 source-frame corners [TL, TR, BR, BL] as JSON.\n"
        "# Coordinates may be negative or beyond original frame bounds.\n"
        f"SRC_POINTS={src_points_json}\n"
        "\n"
        "# BEV canvas dimensions (must match the mask PNG dimensions)\n"
        f"BEV_WIDTH={bev_w}\n"
        f"BEV_HEIGHT={bev_h}\n"
    )


def build_map_svg(shapes: Iterable[dict], width: int, height: int) -> str:
    svg = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}">',
        '  <g class="parking-lot-shapes">',
    ]
    for shape in shapes:
        pts = " ".join(f"{x:.1f},{y:.1f}" for x, y in shape.get("points", []))
        sid = shape.get("id", "")
        if pts:
            svg.append(f'    <polygon points="{pts}" data-id="{sid}"/>')
    svg.append("  </g>")
    svg.append("</svg>")
    svg.append("")
    return "\n".join(svg)


def build_zip(session: Session) -> bytes:
    bev = session.get_bev()
    bev_w = bev["width"] if bev else 1200
    bev_h = bev["height"] if bev else 800

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(".env", build_env(session))

        parking = session.get_mask("parking")
        if parking:
            zf.writestr("assets/parking_mask.png", parking)

        orientation = session.get_mask("orientation")
        if orientation:
            zf.writestr("assets/orientation_zones.png", orientation)

        shapes = session.get_map_shapes()
        if shapes:
            zf.writestr(
                "assets/parking_map.svg", build_map_svg(shapes, bev_w, bev_h)
            )

    return buf.getvalue()


def export_summary(session: Session) -> dict:
    bev = session.get_bev()
    return {
        "camera_url": bool(session.get_camera_url()),
        "bev_calibrated": bev is not None,
        "bev_dimensions": [bev["width"], bev["height"]] if bev else None,
        "parking_mask": session.public_state()["has_parking_mask"],
        "orientation_mask": session.public_state()["has_orientation_mask"],
        "map_shapes_count": len(session.get_map_shapes()),
    }
